version: '3.8'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8089:8089'

  postgres-container:
    image: postgres:16.3
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    # networks:
    #   - common-network

volumes:
  postgres:
# networks:
#   common-network:
#     driver: bridge
