var PathKitInit = (() => {
  var _scriptName = import.meta.url;
  
  return (
async function(moduleArg = {}) {
  var moduleRtn;

var n=moduleArg,aa,ba,ca=new Promise((b,a)=>{aa=b;ba=a}),da="object"==typeof window,ea="undefined"!=typeof WorkerGlobalScope;
(function(b){var a={};b.loadCmdsTypedArray=function(f){for(var k=0,l=0;l<f.length;l++)k+=f[l].length;if(a[k])var m=a[k];else m=new Float32Array(k),a[k]=m;var p=0;for(l=0;l<f.length;l++)for(var r=0;r<f[l].length;r++){var w=f[l][r];"string"===typeof w&&(w=b.SkBits2FloatUnsigned(parseInt(w)));m[p]=w;p++}f=b._malloc(m.length*m.BYTES_PER_ELEMENT);b.HEAPF32.set(m,f/m.BYTES_PER_ELEMENT);return[f,k]};b.FromCmds=function(f){f=b.loadCmdsTypedArray(f);var k=b._FromCmds(f[0],f[1]);b._free(f[0]);return k};var c,
d,e,g,h;b.cubicYFromX=function(f,k,l,m,p){c&&d===f&&e===k&&g===l&&h===m||(c&&c.delete(),c=new b._SkCubicMap([f,k],[l,m]),d=f,e=k,g=l,h=m);return c.computeYFromX(p)};b.cubicPtFromT=function(f,k,l,m,p){c&&d===f&&e===k&&g===l&&h===m||(c&&c.delete(),c=new b._SkCubicMap([f,k],[l,m]),d=f,e=k,g=l,h=m);return c.computePtFromT(p)}})(n);
(function(b){b.onRuntimeInitialized=function(){b.SkPath.prototype.addPath=function(){var a=arguments[0];if(1===arguments.length)this._addPath(a,1,0,0,0,1,0,0,0,1);else if(2===arguments.length){var c=arguments[1];this._addPath(a,c.a,c.c,c.e,c.b,c.d,c.f,0,0,1)}else if(7===arguments.length)c=arguments,this._addPath(a,c[1],c[3],c[5],c[2],c[4],c[6],0,0,1);else if(10===arguments.length)c=arguments,this._addPath(a,c[1],c[2],c[3],c[4],c[5],c[6],c[7],c[8],c[9]);else return console.Ma("addPath expected to take 1, 2, 7, or 10 args. Got "+
arguments.length),null;return this};b.SkPath.prototype.reverseAddPath=function(a){this._reverseAddPath(a);return this};b.SkPath.prototype.arc=function(a,c,d,e,g,h){this._arc(a,c,d,e,g,!!h);return this};b.SkPath.prototype.arcTo=function(a,c,d,e,g){this._arcTo(a,c,d,e,g);return this};b.SkPath.prototype.bezierCurveTo=function(a,c,d,e,g,h){this._cubicTo(a,c,d,e,g,h);return this};b.SkPath.prototype.close=function(){this._close();return this};b.SkPath.prototype.closePath=function(){this._close();return this};
b.SkPath.prototype.conicTo=function(a,c,d,e,g){this._conicTo(a,c,d,e,g);return this};b.SkPath.prototype.cubicTo=function(a,c,d,e,g,h){this._cubicTo(a,c,d,e,g,h);return this};b.SkPath.prototype.dash=function(a,c,d){return this._dash(a,c,d)?this:null};b.SkPath.prototype.ellipse=function(a,c,d,e,g,h,f,k){this._ellipse(a,c,d,e,g,h,f,!!k);return this};b.SkPath.prototype.lineTo=function(a,c){this._lineTo(a,c);return this};b.SkPath.prototype.moveTo=function(a,c){this._moveTo(a,c);return this};b.SkPath.prototype.op=
function(a,c){return this._op(a,c)?this:null};b.SkPath.prototype.quadraticCurveTo=function(a,c,d,e){this._quadTo(a,c,d,e);return this};b.SkPath.prototype.quadTo=function(a,c,d,e){this._quadTo(a,c,d,e);return this};b.SkPath.prototype.rect=function(a,c,d,e){this._rect(a,c,d,e);return this};b.SkPath.prototype.simplify=function(){return this._simplify()?this:null};b.SkPath.prototype.asWinding=function(){return this._asWinding()?this:null};b.SkPath.prototype.isEmpty=function(){return this._isEmpty()};
b.SkPath.prototype.stroke=function(a){a=a||{};a.width=a.width||1;a.miter_limit=a.miter_limit||4;a.cap=a.cap||b.StrokeCap.BUTT;a.join=a.join||b.StrokeJoin.MITER;a.res_scale=a.res_scale||1;return this._stroke(a)?this:null};b.SkPath.prototype.transform=function(){if(1===arguments.length)this._transform(arguments[0]);else if(9===arguments.length){var a=arguments;this._transform(a[0],a[1],a[2],a[3],a[4],a[5],a[6],a[7],a[8])}else return console.Ma("transform expected to take 1 or 9 arguments. Got "+arguments.length),
null;return this};b.SkPath.prototype.trim=function(a,c,d){return this._trim(a,c,!!d)?this:null}}})(n);var q="",fa,ha;
if(da||ea)ea?q=self.location.href:"undefined"!=typeof document&&document.currentScript&&(q=document.currentScript.src),_scriptName&&(q=_scriptName),q.startsWith("blob:")?q="":q=q.slice(0,q.replace(/[?#].*/,"").lastIndexOf("/")+1),ea&&(ha=b=>{var a=new XMLHttpRequest;a.open("GET",b,!1);a.responseType="arraybuffer";a.send(null);return new Uint8Array(a.response)}),fa=async b=>{b=await fetch(b,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);};
var ia=console.log.bind(console),t=console.error.bind(console),x,y,ja=!1,A,C,D,E,F,G,ka,la,ma,na;function oa(){var b=y.buffer;A=new Int8Array(b);D=new Int16Array(b);C=new Uint8Array(b);E=new Uint16Array(b);F=new Int32Array(b);G=new Uint32Array(b);n.HEAPF32=ka=new Float32Array(b);na=new Float64Array(b);la=new BigInt64Array(b);ma=new BigUint64Array(b)}var H=0,I=null;
function pa(b){b="Aborted("+b+")";t(b);ja=!0;b=new WebAssembly.RuntimeError(b+". Build with -sASSERTIONS for more info.");ba(b);throw b;}var qa;async function ra(b){if(!x)try{var a=await fa(b);return new Uint8Array(a)}catch{}if(b==qa&&x)b=new Uint8Array(x);else if(ha)b=ha(b);else throw"both async and sync fetching of the wasm failed";return b}async function sa(b,a){try{var c=await ra(b);return await WebAssembly.instantiate(c,a)}catch(d){t(`failed to asynchronously prepare wasm: ${d}`),pa(d)}}
async function ta(b){var a=qa;if(!x&&"function"==typeof WebAssembly.instantiateStreaming)try{var c=fetch(a,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,b)}catch(d){t(`wasm streaming compile failed: ${d}`),t("falling back to ArrayBuffer instantiation")}return sa(a,b)}var J={},L=b=>{for(;b.length;){var a=b.pop();b.pop()(a)}};function M(b){return this.fromWireType(G[b>>2])}
var N={},O={},ua={},va=n.InternalError=class extends Error{constructor(b){super(b);this.name="InternalError"}},Q=(b,a,c)=>{function d(f){f=c(f);if(f.length!==b.length)throw new va("Mismatched type converter count");for(var k=0;k<b.length;++k)P(b[k],f[k])}b.forEach(f=>ua[f]=a);var e=Array(a.length),g=[],h=0;a.forEach((f,k)=>{O.hasOwnProperty(f)?e[k]=O[f]:(g.push(f),N.hasOwnProperty(f)||(N[f]=[]),N[f].push(()=>{e[k]=O[f];++h;h===g.length&&d(e)}))});0===g.length&&d(e)},wa={},xa=b=>{if(null===b)return"null";
var a=typeof b;return"object"===a||"array"===a||"function"===a?b.toString():""+b},ya,R=b=>{for(var a="";C[b];)a+=ya[C[b++]];return a},S=n.BindingError=class extends Error{constructor(b){super(b);this.name="BindingError"}};
function za(b,a,c={}){var d=a.name;if(!b)throw new S(`type "${d}" must have a positive integer typeid pointer`);if(O.hasOwnProperty(b)){if(c.Qa)return;throw new S(`Cannot register type '${d}' twice`);}O[b]=a;delete ua[b];N.hasOwnProperty(b)&&(a=N[b],delete N[b],a.forEach(e=>e()))}function P(b,a,c={}){return za(b,a,c)}
var Aa=(b,a,c)=>{switch(a){case 1:return c?d=>A[d]:d=>C[d];case 2:return c?d=>D[d>>1]:d=>E[d>>1];case 4:return c?d=>F[d>>2]:d=>G[d>>2];case 8:return c?d=>la[d>>3]:d=>ma[d>>3];default:throw new TypeError(`invalid integer width (${a}): ${b}`);}},Ca=b=>{throw new S(b.fa.ia.ga.name+" instance already deleted");},Da=!1,Ea=()=>{},T=b=>{if("undefined"===typeof FinalizationRegistry)return T=a=>a,b;Da=new FinalizationRegistry(a=>{a=a.fa;--a.count.value;0===a.count.value&&(a.ka?a.pa.oa(a.ka):a.ia.ga.oa(a.ha))});
T=a=>{var c=a.fa;c.ka&&Da.register(a,{fa:c},a);return a};Ea=a=>{Da.unregister(a)};return T(b)},Fa=[];function Ga(){}
var Ha=(b,a)=>Object.defineProperty(a,"name",{value:b}),Ia={},Ja=(b,a,c)=>{if(void 0===b[a].ja){var d=b[a];b[a]=function(...e){if(!b[a].ja.hasOwnProperty(e.length))throw new S(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${b[a].ja})!`);return b[a].ja[e.length].apply(this,e)};b[a].ja=[];b[a].ja[d.sa]=d}},Ka=(b,a,c)=>{if(n.hasOwnProperty(b)){if(void 0===c||void 0!==n[b].ja&&void 0!==n[b].ja[c])throw new S(`Cannot register public name '${b}' twice`);Ja(n,
b,b);if(n[b].ja.hasOwnProperty(c))throw new S(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);n[b].ja[c]=a}else n[b]=a,n[b].sa=c},La=b=>{b=b.replace(/[^a-zA-Z0-9_]/g,"$");var a=b.charCodeAt(0);return 48<=a&&57>=a?`_${b}`:b};function Ma(b,a,c,d,e,g,h,f){this.name=b;this.constructor=a;this.ra=c;this.oa=d;this.ma=e;this.Oa=g;this.wa=h;this.La=f;this.Sa=[]}
var Na=(b,a,c)=>{for(;a!==c;){if(!a.wa)throw new S(`Expected null or instance of ${c.name}, got an instance of ${a.name}`);b=a.wa(b);a=a.ma}return b};function Oa(b,a){if(null===a){if(this.Ca)throw new S(`null is not a valid ${this.name}`);return 0}if(!a.fa)throw new S(`Cannot pass "${xa(a)}" as a ${this.name}`);if(!a.fa.ha)throw new S(`Cannot pass deleted object as a pointer of type ${this.name}`);return Na(a.fa.ha,a.fa.ia.ga,this.ga)}
function Pa(b,a){if(null===a){if(this.Ca)throw new S(`null is not a valid ${this.name}`);if(this.ya){var c=this.va();null!==b&&b.push(this.oa,c);return c}return 0}if(!a||!a.fa)throw new S(`Cannot pass "${xa(a)}" as a ${this.name}`);if(!a.fa.ha)throw new S(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.xa&&a.fa.ia.xa)throw new S(`Cannot convert argument of type ${a.fa.pa?a.fa.pa.name:a.fa.ia.name} to parameter type ${this.name}`);c=Na(a.fa.ha,a.fa.ia.ga,this.ga);if(this.ya){if(void 0===
a.fa.ka)throw new S("Passing raw pointer to smart pointer is illegal");switch(this.Ua){case 0:if(a.fa.pa===this)c=a.fa.ka;else throw new S(`Cannot convert argument of type ${a.fa.pa?a.fa.pa.name:a.fa.ia.name} to parameter type ${this.name}`);break;case 1:c=a.fa.ka;break;case 2:if(a.fa.pa===this)c=a.fa.ka;else{var d=a.clone();c=this.Ta(c,U(()=>d["delete"]()));null!==b&&b.push(this.oa,c)}break;default:throw new S("Unsupporting sharing policy");}}return c}
function Qa(b,a){if(null===a){if(this.Ca)throw new S(`null is not a valid ${this.name}`);return 0}if(!a.fa)throw new S(`Cannot pass "${xa(a)}" as a ${this.name}`);if(!a.fa.ha)throw new S(`Cannot pass deleted object as a pointer of type ${this.name}`);if(a.fa.ia.xa)throw new S(`Cannot convert argument of type ${a.fa.ia.name} to parameter type ${this.name}`);return Na(a.fa.ha,a.fa.ia.ga,this.ga)}
var Ra=(b,a,c)=>{if(a===c)return b;if(void 0===c.ma)return null;b=Ra(b,a,c.ma);return null===b?null:c.La(b)},Sa={},Ta=(b,a)=>{if(void 0===a)throw new S("ptr should not be undefined");for(;b.ma;)a=b.wa(a),b=b.ma;return Sa[a]},Ua=(b,a)=>{if(!a.ia||!a.ha)throw new va("makeClassHandle requires ptr and ptrType");if(!!a.pa!==!!a.ka)throw new va("Both smartPtrType and smartPtr must be specified");a.count={value:1};return T(Object.create(b,{fa:{value:a,writable:!0}}))};
function Va(b,a,c,d,e,g,h,f,k,l,m){this.name=b;this.ga=a;this.Ca=c;this.xa=d;this.ya=e;this.Ra=g;this.Ua=h;this.Ja=f;this.va=k;this.Ta=l;this.oa=m;e||void 0!==a.ma?this.toWireType=Pa:(this.toWireType=d?Oa:Qa,this.na=null)}
var Wa=(b,a,c)=>{if(!n.hasOwnProperty(b))throw new va("Replacing nonexistent public symbol");void 0!==n[b].ja&&void 0!==c?n[b].ja[c]=a:(n[b]=a,n[b].sa=c)},Xa,W=(b,a)=>{b=R(b);var c=Xa.get(a);if("function"!=typeof c)throw new S(`unknown function pointer with signature ${b}: ${a}`);return c};class Ya extends Error{}
var $a=b=>{b=Za(b);var a=R(b);X(b);return a},ab=(b,a)=>{function c(g){e[g]||O[g]||(ua[g]?ua[g].forEach(c):(d.push(g),e[g]=!0))}var d=[],e={};a.forEach(c);throw new Ya(`${b}: `+d.map($a).join([", "]));},cb=(b,a)=>{for(var c=[],d=0;d<b;d++)c.push(G[a+4*d>>2]);return c};function db(b){for(var a=1;a<b.length;++a)if(null!==b[a]&&void 0===b[a].na)return!0;return!1}
function eb(b,a,c,d,e){var g=a.length;if(2>g)throw new S("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==a[1]&&null!==c,f=db(a),k="void"!==a[0].name,l=g-2,m=Array(l),p=[],r=[];return Ha(b,function(...w){r.length=0;p.length=h?2:1;p[0]=e;if(h){var u=a[1].toWireType(r,this);p[1]=u}for(var v=0;v<l;++v)m[v]=a[v+2].toWireType(r,w[v]),p.push(m[v]);w=d(...p);if(f)L(r);else for(v=h?1:2;v<a.length;v++){var B=1===v?u:m[v-2];null!==a[v].na&&a[v].na(B)}u=k?a[0].fromWireType(w):
void 0;return u})}
for(var fb=b=>{b=b.trim();const a=b.indexOf("(");return-1===a?b:b.slice(0,a)},gb=[],Y=[],hb=b=>{9<b&&0===--Y[b+1]&&(Y[b]=void 0,gb.push(b))},ib=b=>{if(!b)throw new S(`Cannot use deleted val. handle = ${b}`);return Y[b]},U=b=>{switch(b){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const a=gb.pop()||Y.length;Y[a]=b;Y[a+1]=1;return a}},jb={name:"emscripten::val",fromWireType:b=>{var a=ib(b);hb(b);return a},toWireType:(b,a)=>U(a),la:8,readValueFromPointer:M,na:null},
kb=(b,a,c)=>{switch(a){case 1:return c?function(d){return this.fromWireType(A[d])}:function(d){return this.fromWireType(C[d])};case 2:return c?function(d){return this.fromWireType(D[d>>1])}:function(d){return this.fromWireType(E[d>>1])};case 4:return c?function(d){return this.fromWireType(F[d>>2])}:function(d){return this.fromWireType(G[d>>2])};default:throw new TypeError(`invalid integer width (${a}): ${b}`);}},lb=(b,a)=>{var c=O[b];if(void 0===c)throw b=`${a} has unknown type ${$a(b)}`,new S(b);
return c},mb=(b,a)=>{switch(a){case 4:return function(c){return this.fromWireType(ka[c>>2])};case 8:return function(c){return this.fromWireType(na[c>>3])};default:throw new TypeError(`invalid float width (${a}): ${b}`);}},nb="undefined"!=typeof TextDecoder?new TextDecoder:void 0,ob=(b,a=0,c=NaN)=>{var d=a+c;for(c=a;b[c]&&!(c>=d);)++c;if(16<c-a&&b.buffer&&nb)return nb.decode(b.subarray(a,c));for(d="";a<c;){var e=b[a++];if(e&128){var g=b[a++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var h=
b[a++]&63;e=224==(e&240)?(e&15)<<12|g<<6|h:(e&7)<<18|g<<12|h<<6|b[a++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},pb="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,qb=(b,a)=>{var c=b>>1;for(var d=c+a/2;!(c>=d)&&E[c];)++c;c<<=1;if(32<c-b&&pb)return pb.decode(C.subarray(b,c));c="";for(d=0;!(d>=a/2);++d){var e=D[b+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c},rb=(b,a,c)=>{c??=
2147483647;if(2>c)return 0;c-=2;var d=a;c=c<2*b.length?c/2:b.length;for(var e=0;e<c;++e)D[a>>1]=b.charCodeAt(e),a+=2;D[a>>1]=0;return a-d},sb=b=>2*b.length,tb=(b,a)=>{for(var c=0,d="";!(c>=a/4);){var e=F[b+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d},ub=(b,a,c)=>{c??=2147483647;if(4>c)return 0;var d=a;c=d+c-4;for(var e=0;e<b.length;++e){var g=b.charCodeAt(e);if(55296<=g&&57343>=g){var h=b.charCodeAt(++e);g=65536+
((g&1023)<<10)|h&1023}F[a>>2]=g;a+=4;if(a+4>c)break}F[a>>2]=0;return a-d},vb=b=>{for(var a=0,c=0;c<b.length;++c){var d=b.charCodeAt(c);55296<=d&&57343>=d&&++c;a+=4}return a},wb=[],xb={},yb=b=>{var a=xb[b];return void 0===a?R(b):a},zb=()=>{function b(a){a.$$$embind_global$$$=a;var c="object"==typeof $$$embind_global$$$&&a.$$$embind_global$$$==a;c||delete a.$$$embind_global$$$;return c}if("object"==typeof globalThis)return globalThis;if("object"==typeof $$$embind_global$$$)return $$$embind_global$$$;
"object"==typeof global&&b(global)?$$$embind_global$$$=global:"object"==typeof self&&b(self)&&($$$embind_global$$$=self);if("object"==typeof $$$embind_global$$$)return $$$embind_global$$$;throw Error("unable to get global object.");},Ab=b=>{var a=wb.length;wb.push(b);return a},Bb=(b,a)=>{for(var c=Array(b),d=0;d<b;++d)c[d]=lb(G[a+4*d>>2],`parameter ${d}`);return c},Cb=Reflect.construct,Db=[null,[],[]],Eb=Array(256),Fb=0;256>Fb;++Fb)Eb[Fb]=String.fromCharCode(Fb);ya=Eb;
(()=>{let b=Ga.prototype;Object.assign(b,{isAliasOf:function(c){if(!(this instanceof Ga&&c instanceof Ga))return!1;var d=this.fa.ia.ga,e=this.fa.ha;c.fa=c.fa;var g=c.fa.ia.ga;for(c=c.fa.ha;d.ma;)e=d.wa(e),d=d.ma;for(;g.ma;)c=g.wa(c),g=g.ma;return d===g&&e===c},clone:function(){this.fa.ha||Ca(this);if(this.fa.ua)return this.fa.count.value+=1,this;var c=T,d=Object,e=d.create,g=Object.getPrototypeOf(this),h=this.fa;c=c(e.call(d,g,{fa:{value:{count:h.count,ta:h.ta,ua:h.ua,ha:h.ha,ia:h.ia,ka:h.ka,pa:h.pa}}}));
c.fa.count.value+=1;c.fa.ta=!1;return c},["delete"](){this.fa.ha||Ca(this);if(this.fa.ta&&!this.fa.ua)throw new S("Object already scheduled for deletion");Ea(this);var c=this.fa;--c.count.value;0===c.count.value&&(c.ka?c.pa.oa(c.ka):c.ia.ga.oa(c.ha));this.fa.ua||(this.fa.ka=void 0,this.fa.ha=void 0)},isDeleted:function(){return!this.fa.ha},deleteLater:function(){this.fa.ha||Ca(this);if(this.fa.ta&&!this.fa.ua)throw new S("Object already scheduled for deletion");Fa.push(this);this.fa.ta=!0;return this}});
const a=Symbol.dispose;a&&(b[a]=b["delete"])})();
Object.assign(Va.prototype,{Pa(b){this.Ja&&(b=this.Ja(b));return b},Ha(b){this.oa?.(b)},la:8,readValueFromPointer:M,fromWireType:function(b){function a(){return this.ya?Ua(this.ga.ra,{ia:this.Ra,ha:c,pa:this,ka:b}):Ua(this.ga.ra,{ia:this,ha:b})}var c=this.Pa(b);if(!c)return this.Ha(b),null;var d=Ta(this.ga,c);if(void 0!==d){if(0===d.fa.count.value)return d.fa.ha=c,d.fa.ka=b,d.clone();d=d.clone();this.Ha(b);return d}d=this.ga.Oa(c);d=Ia[d];if(!d)return a.call(this);d=this.xa?d.Ka:d.pointerType;var e=
Ra(c,this.ga,d.ga);return null===e?a.call(this):this.ya?Ua(d.ga.ra,{ia:d,ha:e,pa:this,ka:b}):Ua(d.ga.ra,{ia:d,ha:e})}});Y.push(0,1,void 0,1,null,1,!0,1,!1,1);n.count_emval_handles=()=>Y.length/2-5-gb.length;n.print&&(ia=n.print);n.printErr&&(t=n.printErr);n.wasmBinary&&(x=n.wasmBinary);
var Hb={z:()=>pa(""),u:b=>{var a=J[b];delete J[b];var c=a.elements,d=c.length,e=c.map(f=>f.Ba).concat(c.map(f=>f.Ea)),g=a.va,h=a.oa;Q([b],e,f=>{c.forEach((k,l)=>{var m=f[l],p=k.za,r=k.Aa,w=f[l+d],u=k.Da,v=k.Fa;k.read=B=>m.fromWireType(p(r,B));k.write=(B,K)=>{var z=[];u(v,B,w.toWireType(z,K));L(z)}});return[{name:a.name,fromWireType:k=>{for(var l=Array(d),m=0;m<d;++m)l[m]=c[m].read(k);h(k);return l},toWireType:(k,l)=>{if(d!==l.length)throw new TypeError(`Incorrect number of tuple elements for ${a.name}: expected=${d}, actual=${l.length}`);
for(var m=g(),p=0;p<d;++p)c[p].write(m,l[p]);null!==k&&k.push(h,m);return m},la:8,readValueFromPointer:M,na:h}]})},m:b=>{var a=wa[b];delete wa[b];var c=a.va,d=a.oa,e=a.Ia,g=e.map(h=>h.Ba).concat(e.map(h=>h.Ea));Q([b],g,h=>{var f={};e.forEach((k,l)=>{var m=h[l],p=k.za,r=k.Aa,w=h[l+e.length],u=k.Da,v=k.Fa;f[k.Na]={read:B=>m.fromWireType(p(r,B)),write:(B,K)=>{var z=[];u(v,B,w.toWireType(z,K));L(z)},optional:h[l].optional}});return[{name:a.name,fromWireType:k=>{var l={},m;for(m in f)l[m]=f[m].read(k);
d(k);return l},toWireType:(k,l)=>{for(var m in f)if(!(m in l||f[m].optional))throw new TypeError(`Missing field: "${m}"`);var p=c();for(m in f)f[m].write(p,l[m]);null!==k&&k.push(d,p);return p},la:8,readValueFromPointer:M,na:d}]})},t:(b,a,c)=>{a=R(a);P(b,{name:a,fromWireType:d=>d,toWireType:function(d,e){if("bigint"!=typeof e&&"number"!=typeof e)throw new TypeError(`Cannot convert "${xa(e)}" to ${this.name}`);"number"==typeof e&&(e=BigInt(e));return e},la:8,readValueFromPointer:Aa(a,c,-1==a.indexOf("u")),
na:null})},H:(b,a,c,d)=>{a=R(a);P(b,{name:a,fromWireType:function(e){return!!e},toWireType:function(e,g){return g?c:d},la:8,readValueFromPointer:function(e){return this.fromWireType(C[e])},na:null})},j:(b,a,c,d,e,g,h,f,k,l,m,p,r)=>{m=R(m);g=W(e,g);f&&=W(h,f);l&&=W(k,l);r=W(p,r);var w=La(m);Ka(w,function(){ab(`Cannot construct ${m} due to unbound types`,[d])});Q([b,a,c],d?[d]:[],u=>{u=u[0];if(d){var v=u.ga;var B=v.ra}else B=Ga.prototype;u=Ha(m,function(...Ba){if(Object.getPrototypeOf(this)!==K)throw new S(`Use 'new' to construct ${m}`);
if(void 0===z.qa)throw new S(`${m} has no accessible constructor`);var bb=z.qa[Ba.length];if(void 0===bb)throw new S(`Tried to invoke ctor of ${m} with invalid number of parameters (${Ba.length}) - expected (${Object.keys(z.qa).toString()}) parameters instead!`);return bb.apply(this,Ba)});var K=Object.create(B,{constructor:{value:u}});u.prototype=K;var z=new Ma(m,u,K,r,v,g,f,l);if(z.ma){var V;(V=z.ma).Ga??(V.Ga=[]);z.ma.Ga.push(z)}v=new Va(m,z,!0,!1,!1);V=new Va(m+"*",z,!1,!1,!1);B=new Va(m+" const*",
z,!1,!0,!1);Ia[b]={pointerType:V,Ka:B};Wa(w,u);return[v,V,B]})},h:(b,a,c,d,e,g)=>{var h=cb(a,c);e=W(d,e);Q([],[b],f=>{f=f[0];var k=`constructor ${f.name}`;void 0===f.ga.qa&&(f.ga.qa=[]);if(void 0!==f.ga.qa[a-1])throw new S(`Cannot register multiple constructors with identical number of parameters (${a-1}) for class '${f.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);f.ga.qa[a-1]=()=>{ab(`Cannot construct ${f.name} due to unbound types`,h)};
Q([],h,l=>{l.splice(1,0,null);f.ga.qa[a-1]=eb(k,l,null,e,g);return[]});return[]})},a:(b,a,c,d,e,g,h,f)=>{var k=cb(c,d);a=R(a);a=fb(a);g=W(e,g);Q([],[b],l=>{function m(){ab(`Cannot call ${p} due to unbound types`,k)}l=l[0];var p=`${l.name}.${a}`;a.startsWith("@@")&&(a=Symbol[a.substring(2)]);f&&l.ga.Sa.push(a);var r=l.ga.ra,w=r[a];void 0===w||void 0===w.ja&&w.className!==l.name&&w.sa===c-2?(m.sa=c-2,m.className=l.name,r[a]=m):(Ja(r,a,p),r[a].ja[c-2]=m);Q([],k,u=>{u=eb(p,u,l,g,h);void 0===r[a].ja?(u.sa=
c-2,r[a]=u):r[a].ja[c-2]=u;return[]});return[]})},D:(b,a,c)=>{b=R(b);Q([],[a],d=>{d=d[0];n[b]=d.fromWireType(c);return[]})},F:b=>P(b,jb),i:(b,a,c,d)=>{function e(){}a=R(a);e.values={};P(b,{name:a,constructor:e,fromWireType:function(g){return this.constructor.values[g]},toWireType:(g,h)=>h.value,la:8,readValueFromPointer:kb(a,c,d),na:null});Ka(a,e)},c:(b,a,c)=>{var d=lb(b,"enum");a=R(a);b=d.constructor;d=Object.create(d.constructor.prototype,{value:{value:c},constructor:{value:Ha(`${d.name}_${a}`,
function(){})}});b.values[c]=d;b[a]=d},s:(b,a,c)=>{a=R(a);P(b,{name:a,fromWireType:d=>d,toWireType:(d,e)=>e,la:8,readValueFromPointer:mb(a,c),na:null})},g:(b,a,c,d,e,g)=>{var h=cb(a,c);b=R(b);b=fb(b);e=W(d,e);Ka(b,function(){ab(`Cannot call ${b} due to unbound types`,h)},a-1);Q([],h,f=>{Wa(b,eb(b,[f[0],null].concat(f.slice(1)),null,e,g),a-1);return[]})},f:(b,a,c,d,e)=>{a=R(a);-1===e&&(e=4294967295);e=f=>f;if(0===d){var g=32-8*c;e=f=>f<<g>>>g}var h=a.includes("unsigned")?function(f,k){return k>>>0}:
function(f,k){return k};P(b,{name:a,fromWireType:e,toWireType:h,la:8,readValueFromPointer:Aa(a,c,0!==d),na:null})},b:(b,a,c)=>{function d(g){return new e(A.buffer,G[g+4>>2],G[g>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][a];c=R(c);P(b,{name:c,fromWireType:d,la:8,readValueFromPointer:d},{Qa:!0})},G:(b,a)=>{a=R(a);P(b,{name:a,fromWireType:function(c){for(var d=G[c>>2],e=c+4,g,h=e,f=0;f<=d;++f){var k=e+f;if(f==
d||0==C[k])h=h?ob(C,h,k-h):"",void 0===g?g=h:(g+=String.fromCharCode(0),g+=h),h=k+1}X(c);return g},toWireType:function(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e,g="string"==typeof d;if(!(g||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new S("Cannot pass non-string to std::string");var h;if(g)for(e=h=0;e<d.length;++e){var f=d.charCodeAt(e);127>=f?h++:2047>=f?h+=2:55296<=f&&57343>=f?(h+=4,++e):h+=3}else h=d.length;e=h;h=Gb(4+e+1);f=h+4;G[h>>2]=e;if(g){if(g=f,f=e+1,e=C,0<f){f=
g+f-1;for(var k=0;k<d.length;++k){var l=d.charCodeAt(k);if(55296<=l&&57343>=l){var m=d.charCodeAt(++k);l=65536+((l&1023)<<10)|m&1023}if(127>=l){if(g>=f)break;e[g++]=l}else{if(2047>=l){if(g+1>=f)break;e[g++]=192|l>>6}else{if(65535>=l){if(g+2>=f)break;e[g++]=224|l>>12}else{if(g+3>=f)break;e[g++]=240|l>>18;e[g++]=128|l>>12&63}e[g++]=128|l>>6&63}e[g++]=128|l&63}}e[g]=0}}else C.set(d,f);null!==c&&c.push(X,h);return h},la:8,readValueFromPointer:M,na(c){X(c)}})},l:(b,a,c)=>{c=R(c);if(2===a){var d=qb;var e=
rb;var g=sb;var h=f=>E[f>>1]}else 4===a&&(d=tb,e=ub,g=vb,h=f=>G[f>>2]);P(b,{name:c,fromWireType:f=>{for(var k=G[f>>2],l,m=f+4,p=0;p<=k;++p){var r=f+4+p*a;if(p==k||0==h(r))m=d(m,r-m),void 0===l?l=m:(l+=String.fromCharCode(0),l+=m),m=r+a}X(f);return l},toWireType:(f,k)=>{if("string"!=typeof k)throw new S(`Cannot pass non-string to C++ string type ${c}`);var l=g(k),m=Gb(4+l+a);G[m>>2]=l/a;e(k,m+4,l+a);null!==f&&f.push(X,m);return m},la:8,readValueFromPointer:M,na(f){X(f)}})},q:(b,a,c,d,e,g)=>{J[b]={name:R(a),
va:W(c,d),oa:W(e,g),elements:[]}},C:(b,a,c,d,e,g,h,f,k)=>{J[b].elements.push({Ba:a,za:W(c,d),Aa:e,Ea:g,Da:W(h,f),Fa:k})},r:(b,a,c,d,e,g)=>{wa[b]={name:R(a),va:W(c,d),oa:W(e,g),Ia:[]}},k:(b,a,c,d,e,g,h,f,k,l)=>{wa[b].Ia.push({Na:R(a),Ba:c,za:W(d,e),Aa:g,Ea:h,Da:W(f,k),Fa:l})},I:(b,a)=>{a=R(a);P(b,{Va:!0,name:a,la:0,fromWireType:()=>{},toWireType:()=>{}})},o:(b,a,c,d)=>{b=wb[b];a=ib(a);return b(null,a,c,d)},e:(b,a,c,d,e)=>{b=wb[b];a=ib(a);c=yb(c);return b(a,a[c],d,e)},J:hb,v:b=>{if(0===b)return U(zb());
b=yb(b);return U(zb()[b])},d:(b,a,c)=>{var d=Bb(b,a),e=d.shift();b--;var g=Array(b);a=`methodCaller<(${d.map(h=>h.name).join(", ")}) => ${e.name}>`;return Ab(Ha(a,(h,f,k,l)=>{for(var m=0,p=0;p<b;++p)g[p]=d[p].readValueFromPointer(l+m),m+=d[p].la;f=1===c?Cb(f,g):f.apply(h,g);h=[];f=e.toWireType(h,f);h.length&&(G[k>>2]=U(h));return f}))},n:b=>{9<b&&(Y[b+1]+=1)},K:()=>U([]),B:b=>U(yb(b)),A:b=>{var a=ib(b);L(a);hb(b)},E:(b,a)=>{b=lb(b,"_emval_take_value");b=b.readValueFromPointer(a);return U(b)},w:b=>
{var a=C.length;b>>>=0;if(2147483648<b)return!1;for(var c=1;4>=c;c*=2){var d=a*(1+.2/c);d=Math.min(d,b+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(b,d)/65536))-y.buffer.byteLength+65535)/65536|0;try{y.grow(d);oa();var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},y:()=>52,x:function(){return 70},p:(b,a,c,d)=>{for(var e=0,g=0;g<c;g++){var h=G[a>>2],f=G[a+4>>2];a+=8;for(var k=0;k<f;k++){var l=b,m=C[h+k],p=Db[l];0===m||10===m?((1===l?ia:t)(ob(p)),p.length=0):p.push(m)}e+=f}G[d>>
2]=e;return 0}},Z=await (async function(){function b(d){Z=d.exports;y=Z.L;oa();Xa=Z.ca;H--;0==H&&I&&(d=I,I=null,d());return Z}H++;var a={a:Hb};if(n.instantiateWasm)return new Promise(d=>{n.instantiateWasm(a,(e,g)=>{d(b(e,g))})});qa??=n.locateFile?n.locateFile?n.locateFile("pathkit.wasm",q):q+"pathkit.wasm":(new URL("pathkit.wasm",import.meta.url)).href;try{var c=await ta(a);return b(c.instance)}catch(d){return ba(d),Promise.reject(d)}}()),Za=Z.N;n.__Z6ToCmdsRK6PKPath=Z.O;
n.__Z8FromCmdsmi=Z.P;n.__Z7NewPathv=Z.Q;n.__Z8CopyPathRK6PKPath=Z.R;n.__Z6EqualsRK6PKPathS1_=Z.S;n.__Z7IsEmptyRK6PKPath=Z.T;n.__Z11ToSVGStringRK6PKPath=Z.U;n.__Z13FromSVGStringNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEE=Z.V;n.__Z13ApplySimplifyR6PKPath=Z.W;n.__Z14ApplyAsWindingR6PKPath=Z.X;n.__Z11ApplyPathOpR6PKPathRKS_8SkPathOp=Z.Y;n.__Z10MakeFromOpRK6PKPathS1_8SkPathOp=Z.Z;n.__Z12AddToBuilderR11SkOpBuilderRK6PKPath8SkPathOp=Z._;n.__Z14ResolveBuilderR11SkOpBuilder=Z.$;
n.__Z8ToCanvasRK6PKPathN10emscripten3valE=Z.aa;n.__Z8ToPath2DRK6PKPath=Z.ba;var X=n._free=Z.da,Gb=n._malloc=Z.ea;function Ib(){0<H?I=Ib:0<H?I=Ib:(n.calledRun=!0,ja||(Z.M(),aa(n),n.onRuntimeInitialized?.()))}Ib();moduleRtn=ca;


  return moduleRtn;
}
);
})();
export default PathKitInit;
